namespace Code.CubeLayer.Engines
{
    public enum CubeEngineNames
    {
        STARTUP,
        DESTROY_TIMER_STARTUP,
        REVIVE_TIMER_STARTUP,

        UPDATE_SINE_WAVE,
        UPDATE_DIRECTION_SINE_WAVE,

        MOVE,
        FACE_DIRECTION,

        CALCULATE_DISTANCE,
        DESTROY_ON_DISTANCE,

        KILL_CUBE_DISTANCE,
        KILL_CUBE_TIMER,

        DESTROY_TIMER_TICK,
        ADD_TO_DESTROY_TIMER_EXPIRED,
        DESTROY_ON_TIMER_EXPIRED,

        REVIVE_TIMER_TICK,
        ADD_TO_REVIVE_TIMER_EXPIRED,
        REVIVE_ON_TIMER_EXPIRED,

        REVIVE_CUBE_TIMER,
    }
}